# Generated by Django 5.0 on 2023-12-17 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('medio_pago', models.CharField(max_length=100)),
                ('foto_recibo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Labor',
            fields=[
                ('labor_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nombre_labor', models.CharField(max_length=100)),
                ('disponibilidad', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trabajador_id', models.CharField(max_length=100, unique=True)),
                ('foto_id', models.CharField(max_length=100)),
                ('calificacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('usuarios_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('apellidos_usuario', models.CharField(max_length=100)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('contraseña', models.CharField(max_length=200)),
                ('correo_electronico', models.CharField(max_length=100)),
                ('foto_perfil', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=13)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClienteLabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago', models.IntegerField()),
                ('calificacion', models.IntegerField()),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.cliente')),
                ('labor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.labor')),
            ],
        ),
        migrations.CreateModel(
            name='TrabajadorLabor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('labor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.labor')),
                ('trabajador_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.trabajador')),
            ],
        ),
        migrations.AddField(
            model_name='trabajador',
            name='usuarios_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.usuario'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuarios_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.usuario'),
        ),
    ]
